// Generate the constant `exercises`.

import { readdirSync, writeFileSync } from 'fs';

console.log("Generating exercises");

const directories = getDirectories('./oefeningen');

let exerciseTs = `
// This file is generated by running "npm run generate".

import { lazy } from 'react';

export const exercises = [
`;

let exerciseResultTs = `{
`;

directories.forEach((directory, index, collection) => {
  const id = directory.substring(0, 3);
  const name = directory.substring(4);

  console.log("  generating", directory);

  exerciseTs += `
    {
      id: "${id}",
      title: "${directory}",
      name: "${name}",
      component: lazy(() => import('../oefeningen/${directory}/test/Description')),
    },
  `;

  const isLast = index === collection.length - 1;

  exerciseResultTs += `"${id}": false ${isLast ? '' : ','}`;
});

exerciseTs += '];'
exerciseResultTs += '}';

writeFileSync('./src/exercise.ts', exerciseTs);
writeFileSync('./result/exercise-results.json', exerciseResultTs);

console.log("Finished generating exercises");

// UTILS

function getDirectories(source) {
  return readdirSync(source, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .map((dirent) => dirent.name);
}
