
// This file is generated by running "npm run generate".

import { lazy } from 'react';

export const exercises = [

    {
      id: "001",
      title: "001-typescript-primitive-variables",
      name: "typescript-primitive-variables",
      component: lazy(() => import('../oefeningen/001-typescript-primitive-variables/test/Description')),
    },
  
    {
      id: "002",
      title: "002-typescript-array",
      name: "typescript-array",
      component: lazy(() => import('../oefeningen/002-typescript-array/test/Description')),
    },
  
    {
      id: "003",
      title: "003-typescript-functions",
      name: "typescript-functions",
      component: lazy(() => import('../oefeningen/003-typescript-functions/test/Description')),
    },
  
    {
      id: "004",
      title: "004-typescript-object-part-one",
      name: "typescript-object-part-one",
      component: lazy(() => import('../oefeningen/004-typescript-object-part-one/test/Description')),
    },
  
    {
      id: "005",
      title: "005-typescript-object-part-two",
      name: "typescript-object-part-two",
      component: lazy(() => import('../oefeningen/005-typescript-object-part-two/test/Description')),
    },
  
    {
      id: "006",
      title: "006-typescript-nesting",
      name: "typescript-nesting",
      component: lazy(() => import('../oefeningen/006-typescript-nesting/test/Description')),
    },
  
    {
      id: "007",
      title: "007-typescript-maybe-part-one",
      name: "typescript-maybe-part-one",
      component: lazy(() => import('../oefeningen/007-typescript-maybe-part-one/test/Description')),
    },
  
    {
      id: "008",
      title: "008-typescript-maybe-part-two",
      name: "typescript-maybe-part-two",
      component: lazy(() => import('../oefeningen/008-typescript-maybe-part-two/test/Description')),
    },
  
    {
      id: "009",
      title: "009-methods",
      name: "methods",
      component: lazy(() => import('../oefeningen/009-methods/test/Description')),
    },
  
    {
      id: "010",
      title: "010-type-inference-part-one",
      name: "type-inference-part-one",
      component: lazy(() => import('../oefeningen/010-type-inference-part-one/test/Description')),
    },
  
    {
      id: "011",
      title: "011-type-inference-part-two",
      name: "type-inference-part-two",
      component: lazy(() => import('../oefeningen/011-type-inference-part-two/test/Description')),
    },
  
    {
      id: "012",
      title: "012-union-part-one",
      name: "union-part-one",
      component: lazy(() => import('../oefeningen/012-union-part-one/test/Description')),
    },
  
    {
      id: "013",
      title: "013-union-part-two",
      name: "union-part-two",
      component: lazy(() => import('../oefeningen/013-union-part-two/test/Description')),
    },
  
    {
      id: "014",
      title: "014-generics",
      name: "generics",
      component: lazy(() => import('../oefeningen/014-generics/test/Description')),
    },
  
    {
      id: "015",
      title: "015-complex-generics",
      name: "complex-generics",
      component: lazy(() => import('../oefeningen/015-complex-generics/test/Description')),
    },
  
    {
      id: "016",
      title: "016-hello-world",
      name: "hello-world",
      component: lazy(() => import('../oefeningen/016-hello-world/test/Description')),
    },
  
    {
      id: "017",
      title: "017-greeter",
      name: "greeter",
      component: lazy(() => import('../oefeningen/017-greeter/test/Description')),
    },
  
    {
      id: "018",
      title: "018-fragment",
      name: "fragment",
      component: lazy(() => import('../oefeningen/018-fragment/test/Description')),
    },
  
    {
      id: "019",
      title: "019-blocks",
      name: "blocks",
      component: lazy(() => import('../oefeningen/019-blocks/test/Description')),
    },
  
    {
      id: "020",
      title: "020-card",
      name: "card",
      component: lazy(() => import('../oefeningen/020-card/test/Description')),
    },
  
    {
      id: "021",
      title: "021-complex-card",
      name: "complex-card",
      component: lazy(() => import('../oefeningen/021-complex-card/test/Description')),
    },
  
    {
      id: "022",
      title: "022-report-card",
      name: "report-card",
      component: lazy(() => import('../oefeningen/022-report-card/test/Description')),
    },
  
    {
      id: "023",
      title: "023-conditional-refactoring",
      name: "conditional-refactoring",
      component: lazy(() => import('../oefeningen/023-conditional-refactoring/test/Description')),
    },
  
    {
      id: "024",
      title: "024-dice-part-one",
      name: "dice-part-one",
      component: lazy(() => import('../oefeningen/024-dice-part-one/test/Description')),
    },
  
    {
      id: "025",
      title: "025-dice-part-two",
      name: "dice-part-two",
      component: lazy(() => import('../oefeningen/025-dice-part-two/test/Description')),
    },
  
    {
      id: "026",
      title: "026-blocks-with-defaults",
      name: "blocks-with-defaults",
      component: lazy(() => import('../oefeningen/026-blocks-with-defaults/test/Description')),
    },
  
    {
      id: "027",
      title: "027-pokemon-list",
      name: "pokemon-list",
      component: lazy(() => import('../oefeningen/027-pokemon-list/test/Description')),
    },
  
    {
      id: "028",
      title: "028-loop-in-loop",
      name: "loop-in-loop",
      component: lazy(() => import('../oefeningen/028-loop-in-loop/test/Description')),
    },
  
    {
      id: "029",
      title: "029-counter",
      name: "counter",
      component: lazy(() => import('../oefeningen/029-counter/test/Description')),
    },
  
    {
      id: "030",
      title: "030-bmi-calculator",
      name: "bmi-calculator",
      component: lazy(() => import('../oefeningen/030-bmi-calculator/test/Description')),
    },
  
    {
      id: "031",
      title: "031-unit-converter",
      name: "unit-converter",
      component: lazy(() => import('../oefeningen/031-unit-converter/test/Description')),
    },
  
    {
      id: "032",
      title: "032-pokemon-filter",
      name: "pokemon-filter",
      component: lazy(() => import('../oefeningen/032-pokemon-filter/test/Description')),
    },
  
    {
      id: "033",
      title: "033-document-title",
      name: "document-title",
      component: lazy(() => import('../oefeningen/033-document-title/test/Description')),
    },
  
    {
      id: "034",
      title: "034-window-size",
      name: "window-size",
      component: lazy(() => import('../oefeningen/034-window-size/test/Description')),
    },
  
    {
      id: "035",
      title: "035-timer",
      name: "timer",
      component: lazy(() => import('../oefeningen/035-timer/test/Description')),
    },
  
    {
      id: "036",
      title: "036-pokemon-fetch",
      name: "pokemon-fetch",
      component: lazy(() => import('../oefeningen/036-pokemon-fetch/test/Description')),
    },
  
    {
      id: "037",
      title: "037-autofocus",
      name: "autofocus",
      component: lazy(() => import('../oefeningen/037-autofocus/test/Description')),
    },
  
    {
      id: "038",
      title: "038-video-component",
      name: "video-component",
      component: lazy(() => import('../oefeningen/038-video-component/test/Description')),
    },
  
    {
      id: "039",
      title: "039-debounced-search",
      name: "debounced-search",
      component: lazy(() => import('../oefeningen/039-debounced-search/test/Description')),
    },
  
    {
      id: "040",
      title: "040-context",
      name: "context",
      component: lazy(() => import('../oefeningen/040-context/test/Description')),
    },
  
    {
      id: "041",
      title: "041-render-props",
      name: "render-props",
      component: lazy(() => import('../oefeningen/041-render-props/test/Description')),
    },
  
    {
      id: "042",
      title: "042-headless-list",
      name: "headless-list",
      component: lazy(() => import('../oefeningen/042-headless-list/test/Description')),
    },
  ];